config/routes.rb
Abak::Application.routes.draw do
  resources :pages
  root :to                   => 'pages#index'
  get '/:root/add'           => 'pages#newRoot'
  get '/:root'               => 'pages#root'
  get '/:root/*children/add' => 'pages#newChild'
  get '/:root/*children'     => 'pages#child'

end

app/models/page.rb
class Page < ActiveRecord::Base
  acts_as_tree 
  attr_accessible :parent_id, :name, :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include ApplicationHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(params[:page])
    if @page.save
      redirect_to @page, :notice => "Successfully created page."
    else
      render :action => 'new'
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(params[:page])
      redirect_to @page, :notice  => "Successfully updated page."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    redirect_to pages_url, :notice => "Successfully destroyed page."
  end

  # show existing root by name
  # or create new with name
  def root
    @rootName = params[:root]
    @pages = Page.roots.select{|root| root.name == @rootName}
    if @pages.length == 0
      @page = Page.new
      @page.name = @rootName
      render :action => 'new'
    else
      @page = @pages[0]
      render :action => 'show'
    end
  end 

  # edit existing root by name
  # or create new with name
  def newRoot
    @rootName = params[:root]
    @pages = Page.roots.select{|root| root.name == @rootName}
    if @pages.length == 0
      @page = Page.new
      @page.name = @rootName
      render :action => 'new'
    else
      @page = @pages[0]
      render :action => 'edit'
    end
  end

  # show existing child by name
  # or create new with name
  def child
    @rootName = params[:root]
    @pages = Page.roots.select{|root| root.name == @rootName}
    unless @pages.length == 0
      @page = findTreeNamedNode(params[:children].split('/'), @pages[0])
      unless @page.nil?
        render :action => 'show'
      else
        @pages = Page.all
        render :action => 'index'
      end
    else
      @pages = Page.all
      render :action => 'index'
    end
  end
 
  # edit existing root by name
  # or create new with name
  def newChild
    @rootName = params[:root]
    @pages = Page.roots.select{|root| root.name == @rootName}
    unless @pages.length == 0
      @children = params[:children].split('/')
      @page = findTreeNamedNode(@children, @pages[0])
      if @page.nil? # if not yet exists
        @children = params[:children].split('/')
        @ansNames = @children.first(@children.length - 1)
        @ans = findTreeNamedNode(@ansNames, @pages[0])
        if @ans.nil? # if we haven't part of full path for creatng node
          render :action => 'index'
        else
          @page = @ans.children.create("name" => @children.last())
          render :action => 'new'
        end
      else         # if already exists
        render :action => 'edit'
      end
    else
      render :action => 'index'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include PagesHelper
  # trying to avoid js injection
  # look like SQL injection are stil posible

  # **[string]**      => <b>[string]</b>
  # \\[string]\\      => <i>[string]</i>
  # ((path [string])) => <a href="path">[string]</a>
  def translateToShow(str)
    @result = str
    @result.gsub!(/</, '&lt;')
    @result.gsub!(/>/, '&gt;')
    @result.gsub!(/\*{2}(.+)\*{2}/, '<b>\1</b>')
    @result.gsub!(/\\{2}(.+)\\{2}/, '<i>\1</i>')
    @result.gsub!(/\({2}((\/[\S]+)+)\s+(.+)\){2}/, '<a href="\1">\3</a>')
    return @result
  end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  #finding tree node by names array path
  def findTreeNamedNode(names, root)
    if names.length == 0
      return root
    else
      if root.nil?
        return nil
      else
        @name = names.shift
        @nodes = root.children.select{|child| child.name == @name}
        unless @nodes.length == 0
          @node = @nodes[0]
          return findTreeNamedNode(names, @node)
        else
          return nil
        end
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <ul id="menu">
      <% for page in Page.roots %>
         <li><%= link_to h(page.name), page %></li>
      <% end %>
      </ul>
      <div class="clear"></div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for @page do |f| %>
  <%= f.error_messages %>
<!--
  <p>
    <%= f.label :parent_id %><br />
    <%= f.collection_select :parent_id, Page.all(:order => "name"), :id, :name, :include_blank => true %>
  </p>
-->
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/pages/edit.html.erb
<% title "Edit Page" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @page %> |
  <%= link_to "View All", pages_path %>
</p>

app/views/pages/index.html.erb
<% title "Pages" %>

<table>
  <tr>
<!--    <th>Parent</th>  -->
    <th style="width:200px;">Name</th>
    <th>Content</th>
  </tr>
  <% for page in @pages %>
    <tr>
<!--      <td><%= page.parent_id %></td> -->
      <td>
        <p>
<% for p in page.ancestors.reverse %>
          <span style="padding-left:<%= 30 *  page.ancestors.reverse.index(p)      %>tx!important;"> <%= p.name %> </span><br/>
          <span style="padding-left:<%= 30 * (page.ancestors.reverse.index(p) + 1) %>px!important;"> +---  </span>
<% end %>  
          <b><%= page.name %></b>
        </p> 
      </td>
      <td class="index__page__content"><%= page.content %></td>
      <td><%= link_to "Show", page %></td>
      <td><%= link_to "Edit", edit_page_path(page) %></td>
      <td><%= link_to "Destroy", page, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Page", new_page_path %></p>

app/views/pages/new.html.erb
<% title "New Page" %>

<%= render 'form' %>

<p><%= link_to "Back to List", pages_path %></p>

app/views/pages/show.html.erb
<% title @page.ancestors.reverse.map{|n| n.name}.join('/') + '/' + @page.name, false %>

<% unless @page.children.empty? %>
<ul id="submenu">
  <% for page in @page.children %>
    <li><%= link_to h(page.name), page %></li>
  <% end %>
</ul>
<% end %>

<p>
<% for page in @page.ancestors.reverse %>
  <%= link_to h(page.name), page %> &gt;
<% end %>
</p>

<h1><%=h @page.name %></h1>

<%= simple_format(translateToShow(@page.content)) %>

<p>
  <%= link_to "Edit", edit_page_path(@page) %> |
  <%= link_to "Destroy", @page, :confirm => 'sure?', :method => :delete %> |
  <%= link_to "View All", pages_path %>  
</p>